services:
  communico:
    env_file: ../.env
    image: communico:devcontainer
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DOLTGRES_USER: ${DB_USER}
      DOLTGRES_PASSWORD: ${DB_PASS}
      DOLTGRES_DB: ${DB_NAME}
      DOLTGRES_DATA_DIR: ${DB_DATA_DIR}
    ports:
      - "${DB_PORT:-5432}:5432"
      - "${APP_PORT:-8000}:8000"
    volumes:
      - ../doltgres/config:/etc/doltgres/servercfg.d
      - ..:/workspace:cached
    command: sleep infinity
