listener:
  host: 0.0.0.0
  port: 5432

cfg_dir: /etc/doltgres/servercfg.d
data_dir: /opt/doltgres/data
privilege_file: /opt/doltgres/config/privileges.db
branch_control_file: /opt/doltgres/config/branch_control.db
